### ISSUE TITLE
add the Hacktoberfest tag

### ISSUE THREAD

**Issue by satyampgt4** [seeditsolution/pythonprogram#665]
Please add the hacktoberfest tag in the repository.
Otherwise, the pull requests made in this repository will not be counted towards the Hacktoberfest-2020.

following is the status of my pull request on this repository

Hacktoberfest page says :

Ineligible Repository
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.

**Comment by MrHunterOP** [comment]
> Please add the hacktoberfest tag in the repository.
> Otherwise, the pull requests made in this repository will not be counted towards the Hacktoberfest-2020.
> 
> following is the status of my pull request on this repository
> 
> Hacktoberfest page says :
> 
> Ineligible Repository
> Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.

Yes

**Comment by MrHunterOP** [comment]
> Please add the hacktoberfest tag in the repository.
> Otherwise, the pull requests made in this repository will not be counted towards the Hacktoberfest-2020.
> 
> following is the status of my pull request on this repository
> 
> Hacktoberfest page says :
> 
> Ineligible Repository
> Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.

You are a participant?

**Comment by alokku6** [comment]
Please add the hacktoberfest tag in the repository.
Otherwise, the pull requests made in this repository will not be counted towards the Hacktoberfest-2020.

following is the status of my pull request on this repository

Hacktoberfest page says :

Ineligible Repository
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR.
